const products = [
    {
        id: 1,
        name: "Smartphone X",
        category: "Electronics",
        price: 699.99,
        stock: 50,
        sales: 120,
        yearlySales: 1368,
        monthlySale: [
            {
                january: 140,
                february: 120,
                march: 70,
                april: 150,
                may: 110,
                june: 84,
                july: 92,
                august: 110,
                september: 152,
                october: 120,
                november: 100,
                december: 120,
            },
        ],
        dateAdded: "2024-01-15",
    },
    {
        id: 2,
        name: "Leather Jacket",
        category: "Clothing",
        price: 199.99,
        stock: 30,
        sales: 45,
        yearlySales: 700,
        dateAdded: "2024-02-01",
    },
    {
        id: 3,
        name: "Organic Cereal",
        category: "Food",
        price: 4.99,
        stock: 100,
        sales: 75,
        yearlySales: 2000,
        dateAdded: "2024-03-10",
    },
    {
        id: 4,
        name: 'Smart TV 55"',
        category: "Electronics",
        price: 549.99,
        stock: 25,
        sales: 30,
        yearlySales: 200,
        dateAdded: "2024-01-20",
    },
    {
        id: 5,
        name: "Running Shoes",
        category: "Clothing",
        price: 89.99,
        stock: 60,
        sales: 90,
        yearlySales: 1330,
        dateAdded: "2024-02-15",
    },
    {
        id: 6,
        name: "Coffee Maker",
        category: "Home",
        price: 79.99,
        stock: 40,
        sales: 60,
        yearlySales: 500,
        dateAdded: "2024-03-05",
    },
    {
        id: 7,
        name: "Wireless Earbuds",
        category: "Electronics",
        price: 129.99,
        stock: 75,
        sales: 150,
        yearlySales: 1600,
        dateAdded: "2024-01-30",
    },
    {
        id: 8,
        name: "Yoga Mat",
        category: "Fitness",
        price: 29.99,
        stock: 80,
        sales: 100,
        yearlySales: 1400,
        dateAdded: "2024-02-28",
    },
];

localStorage.setItem("product-analysis-data", JSON.stringify(products));
